spring:
  datasource:
    url: jdbc:mysql://localhost:3306/go-volley
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  file:
    name: go_volley.log
  level:
    root: info
backup:
  db:
    name: go-volley
  email:
    host: smtp.gmail.com
    port: 587
    username: go.volley.dev
    password: GoVolley2023
    from: go.volley.dev@gmail.com
    to: bartekpretnik@gmail.com
