spring:
  datasource:
    url: jdbc:mysql://sql7.freesqldatabase.com:3306/sql7601764
    username: sql7601764
    password: QK6tf64IlQ
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
